CREATE DATABASE PROYECTOFACTURACION;
GO
USE PROYECTOFACTURACION;
GO

CREATE TABLE CLIENTES(
	ID_CLIENTE int identity primary key,
	NOMBRE varchar(15) not null,
	APELLIDO1 varchar(15) not null,
	APELLIDO2 varchar(15) NOT NULL,
	DIRECCION varchar(200) NOT NULL,
	TELEFONO varchar(11) NOT NULL,
	CLIENTE_ELIMINADO bit
);

CREATE TABLE PRODUCTOS(
	ID_PRODUCTO INT IDENTITY PRIMARY KEY,
	NOMBRE VARCHAR(20) NOT NULL,
	DESCRIPCION VARCHAR(200) NOT NULL,
	PRECIO DECIMAL NOT NULL,
	PRODUCTO_ELIMINADO BIT
);

CREATE TABLE DETALLEFACTURA(
	ID_DETALLE INT IDENTITY PRIMARY KEY,
	ID_PRODUCTO INT FOREIGN KEY REFERENCES PRODUCTOS(ID_PRODUCTO),
	CANTIDAD INT DEFAULT 1 NOT NULL,
	PRECIO DECIMAL NOT NULL,
	SUBTOTAL DECIMAL NOT NULL,
	DETALLE_ELIMINADO BIT
);

CREATE TABLE FACTURAS(
	ID_FACTURA INT IDENTITY PRIMARY KEY,
	ID_CLIENTE INT FOREIGN KEY REFERENCES CLIENTES(ID_CLIENTE),
	ID_DETALLE INT FOREIGN KEY REFERENCES DETALLEFACTURA(ID_DETALLE),
	FECHA_EMISION DATE DEFAULT GETDATE() NOT NULL,
	FECHA_VENCIMIENTO DATE NOT NULL,
	MONTO_TOTAL DECIMAL NOT NULL,
	ESTADO_PAGO VARCHAR(10) CHECK (ESTADO_PAGO IN('PENDIENTE','CANCELADA','VENCIDA', 'MORORSO')) NOT NULL,
	PAGOS_REALIZADOS int NOT NULL,
	IMPUESTO DECIMAL DEFAULT 0.0 NOT NULL,
	DESCUENTO DECIMAL DEFAULT 0.0 NULL,
	FACTURA_ELIMINADA BIT  
);

CREATE TABLE HISTORIALFINANCIERO(
	ID_HISTORIALFINANCIERO INT IDENTITY PRIMARY KEY,
	ID_FACTURA INT FOREIGN KEY REFERENCES FACTURAS(ID_FACTURA),
	FECHA_PAGO DATE DEFAULT GETDATE() NOT NULL,
	MONTO_PAGO DECIMAL NOT NULL,
	FACTURA_PAGADA CHAR CHECK(FACTURA_PAGADA IN('S','N')) NOT NULL,
	MONTOTOTALDEUDA DECIMAL NOT NULL,
	PAGO_ELIMINADO BIT
);

CREATE TABLE EMPLEADOS(
	ID_EMPLEADO INT IDENTITY PRIMARY KEY,
	NOMBRE VARCHAR(15) NOT NULL,
	APELLIDO1 VARCHAR(15) NOT NULL,
	APELLIDO2 VARCHAR(15) NOT NULL,
	CARGO VARCHAR(20) CHECK (CARGO IN('ADMINISTRADOR','EMPLEADO','CLIENTE')) NOT NULL,
	EMPLEADO_ELIMINADO BIT
);

CREATE TABLE NOTIFICACIONES(
	ID_NOTIFICACION INT IDENTITY PRIMARY KEY,
	ID_EMPLEADO INT FOREIGN KEY REFERENCES EMPLEADOS(ID_EMPLEADO),
	ID_HISTORIALFINANCIERO INT FOREIGN KEY REFERENCES HISTORIALFINANCIERO(ID_HISTORIALFINANCIERO),
	MENSAJE VARCHAR(200) DEFAULT 'CLIENTE EN ATRASO' NOT NULL,
	FECHA_ENVIO DATE DEFAULT GETDATE(),
	DESTINATARIO VARCHAR(15) NOT NULL,
	NOTIFICACION_ELIMINADA BIT
);

CREATE TABLE HISTORIALCLIENTE(
	ID_HISTORIAL INT IDENTITY PRIMARY KEY NOT NULL,
	ID_CLIENTE INT FOREIGN KEY REFERENCES CLIENTES(ID_CLIENTE),
	DESCRIPCION VARCHAR(200) NOT NULL,
	FECHA DATE DEFAULT GETDATE()NOT NULL,
	FACTURA_SELECCIONADA INT NOT NULL,
	HISTORIAL_ELIMINADO BIT
);

CREATE TABLE HISTORIALVENTAS(
	ID_HISTORIALVENTAS INT IDENTITY PRIMARY KEY,
	ID_FACTURA INT FOREIGN KEY REFERENCES FACTURAS(ID_FACTURA),
	MONTOTOTALFACTURA DECIMAL NOT NULL,
	FECHAFACTURAS DATE NOT NULL,
	HISTORIALVENTASELIMINADO BIT 
);

